---
- name: Deploy Nuxt.js Docker Application
  hosts: all
  become: yes

  vars:
    DOCKERHUB_USER: "{{ docker_username }}"
    DOCKERHUB_TOKEN: "{{ docker_token }}"
    DOCKER_IMAGE: "{{ image_name }}"
    CONTAINER_NAME: "{{ container_name }}" 
    DOMAIN_NAME: "{{ domain_name }}"

  tasks:
    # --- FIX 1: Prerequisites for Ansible Docker Modules ---
    # Ansible needs Python's docker library to run docker_login, docker_image, etc.
    - name: Install Docker Python SDK (System Package)
      apt:
        name: python3-docker
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # --- Nginx Installation ---
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable nginx services
      service: 
        name: nginx
        state: started
        enabled: yes

    # --- Docker Operations ---
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKERHUB_USER }}"
        password: "{{ DOCKERHUB_TOKEN }}"

    # --- FIX 2: Fixed invalid module name 'DOCKER_IMAGE' ---
    - name: Pull Nuxt.js Docker Image
      community.docker.docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull
        force_source: yes

    - name: Run Nuxt.js Docker Container
      community.docker.docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ DOCKER_IMAGE }}"
        ports: 
          - "3001:3000"
        state: started
        restart_policy: always
        pull: yes # Ensures we use the new image we just pulled
    
    # --- Nginx Configuration ---
    # --- FIX 3: Fixed typo 'stats' -> 'stat' ---
    - name: Check if Nginx site configuration exists
      stat: 
        path: "/etc/nginx/sites-available/{{ DOMAIN_NAME }}"
      register: nginx_site_config

    - name: Configure Nginx as a reverse proxy for Nuxt.js app
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-available/{{ DOMAIN_NAME }}"
      when: not nginx_site_config.stat.exists

    # --- FIX 4: Fixed Symlink Destination ---
    # You were linking sites-available to sites-available.
    # It must link to sites-enabled to actually work.
    - name: Enable Nginx site configuration
      file:
        src: "/etc/nginx/sites-available/{{ DOMAIN_NAME }}"
        dest: "/etc/nginx/sites-enabled/{{ DOMAIN_NAME }}"
        state: link
      notify: 
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
    - name: Restart Nuxt.js Container
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        state: restarted

    - name: Flush handlers
      meta: flush_handlers

    - name: Restart Nginx forcefully
      service:
        name: nginx
        state: restarted