name: Build and Deploy Nuxt.js App with Ansible to Remote Server

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  SSH_USER: ${{ vars.SSH_USER }}
  TARGET_HOST: ${{ vars.SSH_HOST }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Agent
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          sudo chmod 400 private.key
          eval "$(ssh-agent -s)"
          ssh-add private.key
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create Ansible inventory file
        run: |
          echo "server ansible_host=$TARGET_HOST ansible_user=$SSH_USER ansible_ssh_private_key_file=private.key" > inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini \
            --extra-vars "docker_username=$DOCKER_USERNAME" \
            --extra-vars "docker_token=$DOCKER_TOKEN" \
            --extra-vars "image_name=$CONTAINER_NAME" \
            --extra-vars "domain_name=$DOMAIN_NAME" \
            devops/playbook.yml  

